

POST http://localhost:8000/createUser HTTP/1.1
content-type: application/json

{
    "password": "psswd77",
    "username": "john",
    "email": "go4johne@gmail.com",
    "schoolID": ""
}

###

POST http://localhost:8000/login HTTP/1.1
content-type: application/json

{
    "password": "psswd77",
    "email": "go4johne@gmail.com"
}

###

POST http://localhost:8000/logout HTTP/1.1

###

POST http://localhost:8000/logoutAll HTTP/1.1

###

POST http://localhost:8080/createProf
content-type: application/json

{
    "profName": "ken sdsssllok",
    "schoolID": "12345"
}

###

GET http://localhost:8080/searchProfWithSchoolID/12345/ja
